### ISSUE TITLE
Does not work with Arduino ESP8266?

### ISSUE THREAD

**Issue by Humancell** [ZIOCC/Zio-Qwiic-Loudness-Sensor-I2C#2]
Hello,

I really like this board - ZIO QWIIC LOUDNESS SENSOR (I2C) - and we want to use it in one of our products.  But it will not work with the Arduino ESP8266 for some reason.  I've spent the last several hours attempting to see what it might be, but can not locate the problem.

My board is working with an Arduino UNO.

When I attach it to the ESP8266 it does not work.  I have many other I2C devices that work just fine with this ESP8266, so it is not the ESP8266.

When I run your Example1-Basic_Reading it does discover the board at I2C address 0x38.  If I comment out the get_value(); in loop, the LED *does* blink.  So I2C *writes* are working perfectly.  When it goes to read however the read fails.

The first time through the loop Wire.endTransmission returns 0 (which is good!) but Wire.requestFrom() also returns 0 ... which means no bytes were read.  On all subsequent calls to get_value(); the Wire.endTransmission returns 0x04 ... other error.

It seems that maybe there is an issue with the ESP8266 Wire library talking with your device ... which uses the TinyWire library?

Do you have any suggestions or ideas?

**Comment by Humancell** [comment]
As I have done more research on this issue, numerous people talk about having to update the bootloader of the ATTiny85 to run at 8Mhz ... what speed do you program these to run at?

**Comment by Humancell** [comment]
Hello?  If I can't solve this I really can't buy more of these to integrate into our product.  Any suggestions on how to debug/repair this?

**Comment by Humancell** [comment]
I forgot that I had solved this!

It turns out that you need to enable some I2C clock stretching for the ESP8266 to work with this board.

I used the lines:

```
  Wire.begin();
  Wire.setClock(100000L); //Increase to fast I2C speed!
  Wire.setClockStretchLimit(1000); // Allow for 1000us of clock stretching
```
And now everything works perfectly!

**Comment by icq4ever** [comment]
@Humancell hello. I have similar issue. 
I tried to read multiple loudness sensor with different adress. it works for ~ 1 minutes but soon i got error code 5 from `endTransmission()`. i guess something related with clock speed like you suggest. 

my master device is esp32, and I realised that with esp32, there is no `setClockStretchLimit()` on TwoWire class. 

anyone have similar issue?
